// Customizer const
export const TOGGLE_COLLAPSED_NAV = "TOGGLE_COLLAPSE_MENU";
export const WINDOW_WIDTH = "WINDOW-WIDTH";
export const SWITCH_LANGUAGE = "SWITCH-LANGUAGE";

//Post
export const FETCH_POST_LIST_SUCCESS = "FETCH_POST_LIST_SUCCESS";

//Job
export const FETCH_JOB_LIST_SUCCESS = "FETCH_JOB_LIST_SUCCESS";

//Company
export const FETCH_COMPANY_LIST_SUCCESS = "FETCH_COMPANY_LIST_SUCCESS";

//Data
export const FETCH_SKILL_LIST_SUCCESS = "FETCH_SKILL_LIST_SUCCESS";
export const FETCH_INTEREST_LIST_SUCCESS = "FETCH_INTEREST_LIST_SUCCESS";

//Abuser Report
export const FETCH_ABUSE_REPORT_LIST_SUCCESS = "FETCH_ABUSE_REPORT_LIST_SUCCESS";


//Contact Module const
export const FETCH_START = "fetch_start";
export const FETCH_SUCCESS = "fetch_success";
export const FETCH_ERROR = "fetch_error";
export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";
export const ON_SHOW_LOADER = "ON_SHOW_LOADER";
export const ON_HIDE_LOADER = "ON_HIDE_LOADER";

//Auth const
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";
export const SIGNIN_USER_ERROR = "SIGNIN_USER_ERROR";
export const SIGNOUT_USER = "SIGNOUT_USER";
export const SIGNOUT_USER_SUCCESS = "SIGNOUT_USER_SUCCESS";
export const SIGNOUT_USER_ERROR = "SIGNOUT_USER_ERROR";
export const INIT_URL = "INIT_URL";

//Sticky
export const GET_STICKY = "GET_STICKY";
export const NOTES_UPDATE = "NOTES_UPDATE";
export const FETCH_ALL_NOTES_SUCCESS = "FETCH_ALL_NOTES_SUCCESS";
export const UPDATE_ALL_NOTES_SUCCESS = "UPDATE_ALL_NOTES_SUCCESS";

//Contact
export const GET_All_CONTACT_SUCCESS = "GET_All_CONTACT_SUCCESS";
export const ON_ADD_CONTACT_SUCCESS = "ON_ADD_CONTACT_SUCCESS";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";

export const GOT_USERS = "GOT_USERS";
export const GOT_ONLINE_USERS = "GOT_ONLINE_USERS";
export const GOT_REPORTED_USERS = "GOT_REPORTED_USERS";
export const USER_UPDATED = "USER_UPDATED";
export const GOT_PERMANENT_USERS = "GOT_PERMANENT_USERS";

export const GOT_SPONSORS = "GOT_SPONSORS";

export const GOT_USER_ANALYTICS    = "GOT_USER_ANALYTICS";
export const GOT_SPONSOR_ANALYTICS = "GOT_SPONSOR_ANALYTICS";
export const GOT_PRODUCT_ANALYTICS = "GOT_PRODUCT_ANALYTICS";
